### ISSUE TITLE
Add another stage to linear slide and shorten each, switch to X rail

### ISSUE THREAD

**Issue by rivques** [chsbacon/FTC-CENTERSTAGE-7080#50]
not sure how viable this is. would probably mean adding at least one if not two stages to linear slide. one technique might be to lower the base of the linear slide so we can get more extension per stage (right now we are 3 inches off the ground, limiting total stage length to 9 inches, we could probably go to only 1 inch off the ground allowing 11 inches per stage)

**Comment by rivques** [comment]
related issues that might make this one moot: #48, #51, #52

**Comment by rivques** [comment]
we fit under truss now, and i think that's fine

**Comment by GDamiani2927** [comment]
Reopening for states, now a different purpose. Would involve shortening each extrusion so as to have the extended length be (roughly) equal to what it is now, as we don't really need to get much higher for the way we play the game and that would require having 3 stages. Here are the benefits of executing this:
1. Does #47 if we get it right. Our main issue with hang from the slide is we don't have enough travel to lift the robot because its one point and its all the way at the back. More stages=more travel.
2. Allows our arm to start reach on the board, would be really helpful for auto for reducing bounce. 50 Point autos will be the standard at states, no room for error. 
3. Will maybe get us under 12 inches, allowing travel from both directions under the stage door. Expect large bots at states, flexible travel is super important.

**Comment by GDamiani2927** [comment]
Now that 20342's season is over, we can cannibalize the slide they had planned on using (the one we used last year for POWERPLAY for those who remember), the slide is much smoother with a smaller footprint that allows for a multistage design. It also has pulleys built in, meaning less custom prints that can fail.
https://www.servocity.com/cascading-x-rail-slide-kit/

**Comment by GDamiani2927** [comment]
![Image](https://github.com/chsbacon/FTC-CENTERSTAGE-7080/assets/91289681/800da167-7c04-4ebc-bccc-fad310407d3f)

**Comment by GDamiani2927** [comment]
Unfettered linear slide

![Image](https://github.com/chsbacon/FTC-CENTERSTAGE-7080/assets/91289681/3fc56efe-a1c5-49da-86a4-055e8440de0e)

**Comment by rivques** [comment]
another rigging option

![Image](https://github.com/chsbacon/FTC-CENTERSTAGE-7080/assets/38469076/76458c15-7793-4a15-9df1-164ec9d2787b)

**Comment by GDamiani2927** [comment]
Cad done, next is assembly steps for fab. Good luck!

- [ ] **Cut three X Rails, each to 140 mm.** This should be as precise as possible, it is what determines whether or not we fit under the truss. Mr. Miller may have to do this, just mark on each where we want to cut it.
- [ ] **3d print new mounts for the motor plates.** These are the thick orange pieces in the cad model.
- [ ] **3d print new motor spool.** Spacing is updated, requires a reprint.
- [ ] **Assemble two gantry plates, each with four mini rollers.** These may already be assembled, if not refer to cad for details.
- [ ] **Assemble three pulley mounts to go on linear slide.** I believe two of three are assembled, one more is partially assembled but the main screw is stripped, will have to find a replacement. Use nylon lock nuts for the main screw (the one holding the pulley).
- [ ] **Assemble three pulley mounts to go on baseplate.** These are slightly different from the old ones, so new mounts will have to be 3d printed. The old pulley bearing itself should work fine, just update the mount.
- [ ] **Find the black pieces that go on the ends of the slides.** We should have them all in the lab around the linear slide area but if not, laser cutting should suffice. Pay careful attention to which ones go where and how many go on each end, be faithful to the CAD model, it is accurate.
- [ ] **Assemble full slide and ensure it has smooth motion.**
- [ ] **Attach slide and external pulleys to the baseplate as per the cad model.** Only 6-32 should be necessary.
- [ ] **Mount motor** so that the grooves in the spool are planar with the pulleys. New mounting holes were added for the motor mount, refer to CAD.
- [ ] **Thread return and extensions strings.** The above image explains how to do this with the addition of a pulley for the green return string. Use our standard kevlar string, and make sure all knots are secure. Knots can be tied to the black end pieces.
